.github/workflows/codeql-analysis.yml, .github/workflows/node-build.yml
=> de-parallize client/server as must be serial

cra-client/.env.sample, cra-client/public/index.html, cra-server/functions/getAxiosInstance.js, cra-server/router/routes.js
Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>
Fixes #10
=> Path changes to enable components to load and operate

cra-client/src/components/TypeExplorer/TypeExplorer.js, cra-client/src/components/TypeExplorer/components/details-panel/TypeDisplay.js, cra-client/src/components/TypeExplorer/components/diagram/DiagramManager.js, cra-client/src/components/TypeExplorer/components/diagram/EntityInheritanceDiagram.js, cra-client/src/components/TypeExplorer/components/diagram/EntityNeighborhoodDiagram.js, cra-client/src/components/TypeExplorer/components/focus-controls/FocusControls.js, cra-client/src/components/TypeExplorer/components/resource-selection/DeprecatedAttributeControl.js, cra-client/src/components/TypeExplorer/components/resource-selection/DeprecatedTypeControl.js, cra-client/src/components/TypeExplorer/components/resource-selection/ServerSelector.js, cra-client/src/components/TypeExplorer/contexts/FocusContext.js, cra-client/src/components/TypeExplorer/contexts/RequestContext.js, cra-client/src/components/TypeExplorer/contexts/TypesContext.js
Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>
Fixes #11
=> Updates to Tex for es-linter and consequent changes

cra-client/src/components/RepositoryExplorer/RepositoryExplorer.js, cra-client/src/components/RepositoryExplorer/components/details-panel/InstancePropertiesDisplay.js, cra-client/src/components/RepositoryExplorer/components/diagram/Diagram.js, cra-client/src/components/RepositoryExplorer/components/diagram/DiagramManager.js, cra-client/src/components/RepositoryExplorer/components/graph-controls/GraphControls.js, cra-client/src/components/RepositoryExplorer/components/graph-controls/TraversalResultHandler.js, cra-client/src/components/RepositoryExplorer/components/instance-retrieval/FilterManager.js, cra-client/src/components/RepositoryExplorer/components/instance-retrieval/InstanceSearch.js, cra-client/src/components/RepositoryExplorer/components/resource-selection/ServerSelector.js, cra-client/src/components/RepositoryExplorer/contexts/InstancesContext.js, cra-client/src/components/RepositoryExplorer/contexts/InteractionContext.js
=> Modifications to Rex 

cra-client/src/components/Dino/Dino.js, cra-client/src/components/Dino/components/details-panel/ServerDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerStatusDisplay.js, cra-client/src/components/Dino/components/diagram/DiagramManager.js, cra-client/src/components/Dino/components/diagram/TopologyDiagram.js, cra-client/src/components/Dino/components/resource-selection/PlatformSelector.js, cra-client/src/components/Dino/components/resource-selection/ServerSelector.js, cra-client/src/components/Dino/contexts/ResourcesContext.js
=> Modifications to Dino following move to new repo and es-linter

cra-client/src/components/RepositoryExplorer/components/diagram/Diagram.js
Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>
Fixes #22
=> Fix label positioning code

README.md
=> git24 amend readme errors

cra-client/src/app.scss, cra-client/src/components/Home.js, cra-client/src/images/odpi/Egeria_logo_color_400.js
=> #28 add home screen

.github/workflows/node-build.yml
Aims to correct conditional used so that we only publish to dockerhub after a merge build, not on a PR
=> #1 change conditional for merge build

.github/workflows/node-build.yml
Corrects name of secrets
(Unfortunately actions need testing by pushing through the PR process.....)
=> #1 correct secrets reference for docker publish

.github/workflows/node-build.yml
=> publish to odpi repo

cra-client/src/components/Dino/components/details-panel/EngineServiceDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerServicesDisplay.js, cra-client/src/components/Dino/components/details-panel/ServiceDisplay.js, cra-client/src/components/Dino/contexts/ResourcesContext.js
Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>
=> Adds engine service handling to Dino

cra-client/src/components/Dino/components/details-panel/DetailsPanel.js, cra-client/src/components/Dino/components/details-panel/EngineDisplay.js, cra-client/src/components/Dino/components/details-panel/EngineServiceDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerServicesDisplay.js, cra-client/src/components/Dino/components/diagram/DiagramManager.js, cra-client/src/components/Dino/contexts/RequestContext.js, cra-client/src/components/Dino/contexts/ResourcesContext.js, cra-client/src/components/RepositoryExplorer/components/graph-controls/GraphControls.js
=> Adds retrieval and display of governance engines and their governance services

.github/workflows/node-build.yml
=> #46 only run docker action for merge build - skip unless odpi repo

cra-client/package.json, cra-client/src/components/GlossaryAuthor/components/GlossaryQuickTerms.js, cra-client/src/components/GlossaryAuthor/components/navigations/GlossaryAuthorTermsNavigation.js, cra-client/src/components/GlossaryAuthor/components/navigations/StartingNodeNavigation.js, cra-client/src/components/GlossaryAuthor/components/views/NodeTableView.js, cra-client/src/components/ServerAuthor/BasicConfig.js, cra-server/db/users.js
Fix the audit error, some linter issues and removed the short names from the user list
=> #52 fix audit error and linter issues

README.md, cra-client/package.json, cra-client/src/components/GlossaryAuthor/components/navigations/StartingNodeNavigation.js, cra-server/package.json
A return null was added to resolve a linting issue; it regresses the UI; so the return null has been removed in this fix
=> Git54 Amend the name and versions for npm

.gitignore, cra-client/src/Frame.js, cra-client/src/components/Home.js, cra-client/src/components/ServerAuthor/ConfigurationSteps.js, cra-client/src/contexts/ServerAuthorContext.js
Signed-off-by: Sirbu Nicolae-Cezar <sirbunicolaecezar@gmail.com>
=> Fix some build warnings

cra-client/src/components/Dino/components/details-panel/ServerCohortsDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerDisplay.js
=> Egeria react UI 61

.github/workflows/node-build.yml
Fixes #58 
This PR will allow publishing of docker images with both the version string from the cra-server/package.json - for all releases - , and also with :latest for main only
=> #58 Support docker builds per release

.github/workflows/node-build.yml
=> #58 correct github repo name and rename docker image to egeria-react-ui

.github/workflows/codeql-analysis.yml, .github/workflows/node-build.yml, cra-client/package.json, cra-server/package.json
Updates npm version for release
=> #59 update npm version for release

README.md
=> Update README (main)

cra-client/package.json
* Switches from node-saas to regular saas (dart) 1.32.7 as per https://www.npmjs.com/package/sass
Fixes #79
Opening for comment and review. So far I've verified the basic UI starts up, but I am not familar enough with the saas usage to warrant this change is safe. Looking for input from the experts :-)
=> #79 switch to dart saas

cra-client/src/App.js, cra-client/src/auth/NoServerName.js, cra-client/src/auth/login.js
=> #41 handle untentanted url

cra-client/src/auth/NoServerName.js, cra-client/src/auth/login.js, cra-server/db/users.js, cra-server/functions/getServerInfoFromEnv.js, cra-server/functions/serverNameMiddleware.js, cra-server/index.js, cra-server/router/routes.js
=> #89 amend login logic to handle incorrect server name more elegantly

Dockerfile, README.md, cra-client/package.json, cra-server/package.json
=> update version to 2.8 snapshot

.github/workflows/codeql-analysis.yml, .github/workflows/node-build.yml, Dockerfile, README.md, cra-client/package.json, cra-server/package.json
Updates version to 2.7 for release
=> #92 update version to 2.7

.github/dependabot.yml
=> #78 correct dup entry in dependabot config

.github/dependabot.yml
When executes, action reports it needs path set to / -> corrected
=> Update dependabot github action check

cra-client/src/components/GlossaryAuthor/components/visualisation/components/graph-controls/HistoryResultHandler.js, cra-client/src/components/GlossaryAuthor/components/visualisation/contexts/InstancesContext.js
=> #109 fix history in glove

cra-client/src/components/GlossaryAuthor/_glossaryAuthor.scss, cra-client/src/components/GlossaryAuthor/components/TaskDropDown.js, cra-client/src/components/GlossaryAuthor/components/properties/RelationshipTypes.js, cra-client/src/components/GlossaryAuthor/components/views/RelationshipsView.js, cra-client/src/components/GlossaryAuthor/components/visualisation/HELP.md, cra-client/src/components/GlossaryAuthor/components/visualisation/components/details-panel/InstanceDisplay.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/details-panel/RelationshipDisplay.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/diagram/DiagramManager.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/graph-controls/GraphControls.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/graph-controls/TraversalResultHandler.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/instance-retrieval/FilterManager.js, cra-client/src/components/GlossaryAuthor/components/visualisation/contexts/InstancesContext.js, docs/GlossaryAuthor/GlossaryAuthorGuide.md, docs/design/glossary-author/README.md
=> #116 change Line to relationship in glossary author

README.md, cra-client/package.json, cra-server/package.json
=> #123 update version to 2.9rc

.github/workflows/codeql-analysis.yml, .github/workflows/node-build.yml, README.md, cra-client/package.json, cra-server/package.json
=> Update version to 2.8

.github/workflows/codeql-analysis.yml, .github/workflows/node-build.yml
=> #123 fix build for release branches

cra-client/src/components/GlossaryAuthor/GlossaryAuthor.js, cra-client/src/components/GlossaryAuthor/components/GlossaryAuthorBreadCrumb.js, cra-client/src/components/GlossaryAuthor/components/GlossaryQuickTerms.js, docs/design/glossary-author/README.md
=> #30 add breadcrumb

cra-client/src/components/GlossaryAuthor/components/update/UpdateNode.js
=> #133 readonly check on edit

README.md, cra-client/package.json, cra-server/package.json
=> Up version to 2.10 (rc)

README.md, cra-client/package.json, cra-server/package.json
=> Update version to 2.9 for release

cra-client/src/components/GlossaryAuthor/components/nodepages/NodeInput.js, cra-client/src/components/GlossaryAuthor/components/update/UpdateNodeInline.js, cra-client/src/components/GlossaryAuthor/components/visualisation/glove.scss
=> #164 use nodeinput with validation for update in  glove

README.md, cra-client/package.json, cra-server/package.json
=> #167 update version for main to 2.11 rc

README.md, cra-client/package.json, cra-server/package.json
=> #167 update version to 2.10

cra-client/src/components/GlossaryAuthor/components/navigations/StartingNodeNavigation.js
=> #181 replace .* in search criteria with flag

cra-client/src/components/GlossaryAuthor/components/create/CreateRelationshipWizard.js, cra-client/src/components/GlossaryAuthor/components/properties/RelationshipTypes.js
=> #186 use the new isatypeof

.github/workflows/node-build.yml
- Adds display of node, npm version to assist in debugging #138 
- Corrects missing variable syntax for naming upload artifact
=> #138 add display of node/npm version during build

cra-client/src/components/GlossaryAuthor/components/navigations/StartingNodeNavigation.js, cra-client/src/components/GlossaryAuthor/components/update/DeleteButtonWidget.js, cra-client/src/components/GlossaryAuthor/components/update/DeleteNodeWizard.js, cra-client/src/components/GlossaryAuthor/components/update/DeleteRelationshipWizard.js, cra-client/src/components/GlossaryAuthor/components/update/DeleteWizard.js
=> #181 use new  search flags

cra-client/src/components/GlossaryAuthor/components/authoringforms/RelationshipInput.js, cra-client/src/components/GlossaryAuthor/components/authoringforms/RelationshipReadOnly.js, cra-client/src/components/GlossaryAuthor/components/delete/DeleteRelationshipWizard.js, cra-client/src/components/GlossaryAuthor/components/navigations/SearchWizard.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/diagram/Diagram.js, cra-client/src/components/GlossaryAuthor/components/visualisation/contexts/InstancesContext.js, cra-client/src/components/RepositoryExplorer/components/diagram/Diagram.js
=> #194 make select relationship work in glove

cra-client/src/components/GlossaryAuthor/components/visualisation/contexts/InstancesContext.js
=> #199 correct update processing in glove

cra-client/src/components/GlossaryAuthor/components/navigations/SearchNodeWizard.js, cra-client/src/components/GlossaryAuthor/components/navigations/SearchWizard.js
=> #195 fix add to canvas

cra-client/src/components/GlossaryAuthor/components/navigations/GlossaryAuthorChildCategoriesNavigation.js, cra-client/src/components/GlossaryAuthor/components/navigations/GlossaryAuthorTermsNavigation.js
=> #183 allow nested categories to be shown

cra-client/src/components/GlossaryAuthor/components/authoringforms/NodeInput.js, cra-client/src/components/GlossaryAuthor/components/authoringforms/NodeReadOnly.js
=> #204 add glove checking for no attributes

cra-client/src/components/GlossaryAuthor/components/NodeCard/NodeCard.js, cra-client/src/components/GlossaryAuthor/components/NodeCard/_nodeCard.scss
=> #208 correct overflow in glossary author card view

cra-client/package.json, cra-server/package.json
=> Update to rel 2.11

cra-client/package.json, cra-server/package.json
Updates version in main to version 3
=> Update to rel.3

site/docs/contributors/contributorguide.md, site/docs/ecosystem/RepositoryExplorerGuide.md, site/docs/ecosystem/ecosystem.md, site/docs/getting-started/prereqs.md, site/docs/getting-started/setup.md, site/docs/overview/Overview.md, site/docs/solutions/GlossaryAuthor/GlossaryAuthorGuide.md, site/docs/solutions/solutions.md
=> #213 remove duplicate licence from docs pages

cra-client/package.json, cra-server/package.json
Updates version to align with 3.1 (master) of egeria
=> Update version to 3.1 rc

cra-client/package.json, cra-server/package.json
=> Update version to 3.0 for release

cra-client/src/components/GlossaryAuthor/components/visualisation/components/graph-controls/CreateRelationshipButtonWidget.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/graph-controls/DeleteButtonWidget.js, cra-client/src/components/GlossaryAuthor/components/visualisation/components/graph-controls/UpdateButtonWidget.js
=> #222 disable update and delete on anchor relationships

cra-client/src/components/ServerAuthor/components/ServerAuthorWizard.jsx
=> #224 change handling if Crux cannot be enabled 

cra-client/src/components/ServerAuthor/components/ServerAuthorWizard.jsx, cra-client/src/components/ServerAuthor/components/defaults/serverConfigElements.js, cra-client/src/components/ServerAuthor/components/defaults/serverTypes.js
=> #251 amend incorrect working in server author

cra-client/src/components/ServerAuthor/components/ConfigureAuditLogDestinations.jsx, cra-client/src/components/ServerAuthor/contexts/ServerAuthorContext.js
=> #252 allow altering of type and severities in audit log destination

cra-client/package.json, cra-server/package.json
Updates version for release to 3.2.0
=> Update version to 3.2 for release

cra-client/package.json, cra-server/package.json
=> Update main to 3.3 rc

cra-client/src/components/Dino/components/details-panel/ServerConfigEventBusDisplay.js, cra-client/src/components/TypeExplorer/components/diagram/EntityInheritanceDiagram.js, cra-client/src/components/TypeExplorer/components/diagram/EntityNeighborhoodDiagram.js, cra-client/src/components/TypeExplorer/components/focus-controls/FocusControls.js, cra-client/src/components/TypeExplorer/contexts/FocusContext.js
Merges commits from @davidradl  :
#269 TEX 
#270 Dino
For the 3.2 release
=> (Release 3.2) Additional fixes for type explorer & Dino

cra-client/src/components/Dino/components/details-panel/ServerConfigEventBusDisplay.js, cra-client/src/components/Dino/components/details-panel/ServerConfigRepositoryServicesDisplay.js
Adds fix for #264 to release-3.3
=> #264 fixed formatting in dino

.github/workflows/node-build.yml
Add platforms for multi-architecture images
This is related to https://github.com/odpi/egeria/issues/2391
Signed-off-by: Theo Thomas <tcn.thomas@googlemail.com>
=> Add ARM64 to Docker build

cra-client/package.json, cra-server/package.json
Updates branch to 3.4.0 ready for release
=> odpi/egeria#5929 update branch to 3.4.0 for release

cra-client/package.json, cra-server/package.json
Updates main to 3.5 prerelease
=> odpi/egeria#5929 update main to 3.5.0-rc.0

cra-client/src/components/ServerAuthor/contexts/ServerAuthorContext.js
=> #288 refresh the server list after an add

README.md
=> #318 fix readme

README.md, docs/security-fixes.md
=> #344 document findings

cra-client/package.json, cra-server/package.json
=> git352 create 3.5 release changes

cra-client/package.json, cra-server/package.json
=> git352 update packages in main

cra-client/src/components/ServerAuthor/components/accessServices/ConfigureAccessServices.jsx, cra-client/src/components/ServerAuthor/contexts/ServerAuthorContext.js
=> #363 amend access service options remove

cra-client/package.json, cra-server/package.json
=> git383 correct release in main

cra-client/src/components/RepositoryExplorer/components/instance-retrieval/HistoricalDateTime.jsx, cra-client/src/components/RepositoryExplorer/contexts/InstancesContext.js
=> git427 correct spelling

cra-client/src/components/RepositoryExplorer/contexts/InstancesContext.js
=> git427 correct time resetting

cra-client/package.json, cra-server/package.json
Updates version to 3.9.0-rc.0 now that 3.8 has been released
=> #436 Update version to 3.9 rc

cra-client/package.json, cra-server/package.json
See #436
Updates version to 3.8.0 for release
=> #436 Update version to 3.8

cra-client/package.json, cra-server/package.json
=> git466 release 3.10-rc in main

cra-client/src/components/GlossaryAuthor/components/visualisation/components/details-panel/InstancePropertiesDisplay.js, cra-client/src/components/RepositoryExplorer/components/details-panel/InstancePropertiesDisplay.js
=> git637 remove unnecessary alerts

cra-client/package.json, docs/security-fixes.md
=> git645 address vulnerabilities

.github/workflows/stale.yml
Corrects stale workflow to respect 'pinned' label
=> Correct stale workflow - pinned label
